Update to Debian 12 (Bookworm). Configure UnattendedUpgrades to auto update tor.

diff --git a/scripts/docker-entrypoint b/scripts/docker-entrypoint
--- a/scripts/docker-entrypoint
+++ b/scripts/docker-entrypoint
@@ -16,6 +16,12 @@ chmodf 600 /var/lib/tor
 
 if [ ! -e /tor-config-done ]; then
     touch /tor-config-done   # only run this once
+    if [ -n "${TOR_DEBUG}" ]; then
+      if ! grep -q '^PublishServerDescriptor ' /etc/tor/torrc; then
+        echo "Setting PublishServerDescriptor: 0"
+        echo -e "\nPublishServerDescriptor 0" >> /etc/tor/torrc
+      fi
+    fi
 
     # Add Nickname from env variable or randomized, if none has been set
     if ! grep -q '^Nickname ' /etc/tor/torrc; then
@@ -62,6 +68,53 @@ if [ ! -e /tor-config-done ]; then
     if ! grep -q '^DataDirectory ' /etc/tor/torrc; then
         echo -e "\\nDataDirectory /var/lib/tor" >> /etc/tor/torrc
     fi
+
+    # Set the hard limit of open file descriptors really high.
+    # Tor will also potentially run out of ports.
+    echo "Setting ulimit..."
+    ulimit -SHn 65000
+
+    #echo "Setting nameservers..."
+    #echo "nameserver 8.8.8.8" >> /etc/resolv.conf
+    #echo "nameserver 4.2.2.2" >> /etc/resolv.conf
+
+    #echo "Tune using sysctl..."
+    #sudo sysctl net.ipv4.tcp_rmem="4096 87380 16777216"
+    #sudo sysctl net.ipv4.tcp_wmem="4096 65536 16777216"
+    #sudo sysctl net.core.netdev_max_backlog=2500
+    #sudo sysctl net.ipv4.tcp_no_metrics_save=1
+    #sudo sysctl net.ipv4.tcp_moderate_rcvbuf=1
+    #sudo sysctl net.core.rmem_max=1048575
+    #sudo sysctl net.core.wmem_max=1048575
+    #sudo sysctl net.ipv4.ip_local_port_range="1025 61000"
+    #sudo sysctl net.ipv4.tcp_synack_retries=3
+    #sudo sysctl net.ipv4.tcp_tw_recycle=1
+    #sudo sysctl net.ipv4.tcp_max_syn_backlog=10240
+    #sudo sysctl net.ipv4.tcp_fin_timeout=30
+    #sudo sysctl net.ipv4.tcp_keepalive_time=1200
+    #sudo sysctl net.netfilter.nf_conntrack_tcp_timeout_established=7200
+    #sudo sysctl net.netfilter.nf_conntrack_checksum=0
+    #sudo sysctl net.netfilter.nf_conntrack_max=131072
+    #sudo sysctl net.netfilter.nf_conntrack_tcp_timeout_syn_sent=15
+    #sudo sysctl net.ipv4.tcp_keepalive_time=60
+    #sudo sysctl net.ipv4.tcp_keepalive_time=60
+    #sudo sysctl net.ipv4.tcp_keepalive_intvl=10
+    #sudo sysctl net.ipv4.tcp_keepalive_probes=3
+    #sudo sysctl net.ipv4.ip_local_port_range="1025 65530"
+    #sudo sysctl net.core.netdev_max_backlog=300000
+    #sudo sysctl net.core.somaxconn=20480
+    #sudo sysctl net.ipv4.tcp_max_tw_buckets=2000000
+    #sudo sysctl net.ipv4.tcp_timestamps=0
+    #sudo sysctl vm.min_free_kbytes=65536
+    #sudo sysctl net.ipv4.ip_forward=1
+    #sudo sysctl net.ipv4.tcp_syncookies=1
+    #sudo sysctl net.ipv4.tcp_synack_retries=2
+    #sudo sysctl net.ipv4.conf.default.forwarding=1
+    #sudo sysctl net.ipv4.conf.default.proxy_arp=1
+    #sudo sysctl net.ipv4.conf.all.rp_filter=1
+    #sudo sysctl net.ipv4.conf.default.send_redirects=1
+    #sudo sysctl net.ipv4.conf.all.send_redirects=0
+
 fi
 
 echo -e "\n========================================================"
